# Generated by Django 4.2.4 on 2023-08-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="name",
            field=models.CharField(default="test", max_length=50),
            preserve_default=False,
        ),
    ]
